### ISSUE TITLE
Problems in back office 

### ISSUE THREAD

**Issue by yamcell** [MAGOWARE/backoffice-administration#72] opened 2019-10-15 09:55 UTC
Tv show área
Episode and season never show up in User side 
Import movie from tmbd not work after fild all request. Never zafe in data base 

VoD límite in data base are set limitted to vod and live tv
Limited device login same time not work client van login from múltiple device 
And few more 
But mr @irisstaro like always in Best support ever say in this next update all this will be fix
We are waiting One year for TV show área work property.

**Comment by irisstaro** [comment] 2019-11-06 13:21
The problem is fixed on the latest updates of backoffice

**Closed by irisstaro** 2019-11-06 13:21 UTC
